[package]
name = "arm_vgic"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
tock-registers = "0.8"
spin = { version = "0.9.4", features = ["use_ticket_mutex"] }
arm_gic = { path = "../../arceos/crates/arm_gic" }
# serde = { version = "1.0.201", features = ["derive"] }